require 'snacks'
return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  ---@type snacks.Config
  opts = {},
  --     -- your configuration comes here
  --     -- or leave it empty to use the default settings
  --     -- refer to the configuration section below
  --     animate = {
  --       enabled = true,
  --       ---@class snacks.animate.Config
  --       ---@field easing? snacks.animate.easing|snacks.animate.easing.Fn
  --       {
  --         ---@type snacks.animate.Duration|number
  --         duration = 20, -- ms per step
  --         easing = 'linear',
  --         fps = 60, -- frames per second. Global setting for all animations
  --       },
  --     },
  --     bigfile = { enabled = false },
  --     dashboard = {
  --       enabled = true,
  --       sections = {
  --         { section = 'header' },
  --         {
  --           pane = 2,
  --           section = 'terminal',
  --           cmd = 'echo ',
  --           height = 5,
  --           padding = 1,
  --
  --           { section = 'keys', gap = 1, padding = 1 },
  --           { pane = 2, icon = ' ', title = 'Recent Files', section = 'recent_files', indent = 2, padding = 1 },
  --           { pane = 2, icon = ' ', title = 'Projects', section = 'projects', indent = 2, padding = 1 },
  --           {
  --             pane = 2,
  --             icon = ' ',
  --             title = 'Git Status',
  --             section = 'terminal',
  --             enabled = function()
  --               return Snacks.git.get_root() ~= nil
  --             end,
  --             cmd = 'git status --short --branch --renames',
  --             height = 5,
  --             padding = 1,
  --             ttl = 5 * 60,
  --             indent = 3,
  --           },
  --           { section = 'startup' },
  --         },
  --       },
  --       debug = { enabled = false },
  --       dim = { enabled = true },
  --       explorer = { enabled = false },
  --       git = { enabled = false },
  --       gitbrowse = {
  --         enabled = true,
  --         url_patterns = {
  --           ['gitlab.enms.ndc.nasa.gov'] = {
  --             branch = '/-/tree/{branch}',
  --             file = '/-/blob/{branch}/{file}#L{line_start}-L{line_end}',
  --             permalink = '/-/blob/{commit}/{file}#L{line_start}-L{line_end}',
  --             commit = '/-/commit/{commit}',
  --           },
  --         },
  --       },
  --       image = { enabled = false },
  --       indent = { enabled = false },
  --       input = { enabled = false },
  --       layout = { enabled = false },
  --       lazygit = { enabled = false },
  --       notifier = { enabled = true },
  --       notify = { enabled = true },
  --       picker = { enabled = true },
  --       profiler = { enabled = false },
  --       quickfile = { enabled = true },
  --       rename = { enabled = false },
  --       scope = { enabled = true },
  --       scratch = { enabled = false },
  --       scroll = {
  --         enabled = true,
  --         animate = {
  --           duration = { step = 15, total = 250 },
  --           easing = 'linear',
  --         },
  --         -- faster animation when repeating scroll after delay
  --         animate_repeat = {
  --           delay = 100, -- delay in ms before using the repeat animation
  --           duration = { step = 5, total = 50 },
  --           easing = 'linear',
  --         },
  --         -- what buffers to animate
  --         filter = function(buf)
  --           return vim.g.snacks_scroll ~= false and vim.b[buf].snacks_scroll ~= false and vim.bo[buf].buftype ~= 'terminal'
  --         end,
  --       },
  --       statuscolumn = { enabled = true },
  --       terminal = { enabled = false },
  --       toggle = { enabled = true },
  --       util = { enabled = true },
  --       win = { enabled = false },
  --       words = { enabled = true },
  --       styles = {
  --         notification = {
  --           wo = { wrap = true },
  --         },
  --       },
  --       zen = { enabled = false },
  --       keys = {
  --         -- Non Picker related key mappings  {{{
  --         {
  --           '<leader>z',
  --           function()
  --             Snacks.zen()
  --           end,
  --           desc = 'Toggle Zen Mode',
  --         },
  --         {
  --           '<leader>Z',
  --           function()
  --             Snacks.zen.zoom()
  --           end,
  --           desc = 'Toggle Zoom',
  --         },
  --         {
  --           '<leader>.',
  --           function()
  --             Snacks.scratch()
  --           end,
  --           desc = 'Toggle Scratch Buffer',
  --         },
  --         {
  --           '<leader>S',
  --           function()
  --             Snacks.scratch.select()
  --           end,
  --           desc = 'Select Scratch Buffer',
  --         },
  --         {
  --           '<leader>n',
  --           function()
  --             Snacks.notifier.show_history()
  --           end,
  --           desc = 'Notification History',
  --         },
  --         {
  --           '<leader>bd',
  --           function()
  --             Snacks.bufdelete()
  --           end,
  --           desc = 'Delete Buffer',
  --         },
  --         {
  --           '<leader>cR',
  --           function()
  --             Snacks.rename.rename_file()
  --           end,
  --           desc = 'Rename File',
  --         },
  --         {
  --           '<leader>gB',
  --           function()
  --             Snacks.gitbrowse()
  --           end,
  --           desc = 'Git Browse',
  --           mode = { 'n', 'v' },
  --         },
  --         {
  --           '<leader>gg',
  --           function()
  --             Snacks.lazygit()
  --           end,
  --           desc = 'Lazygit',
  --         },
  --         {
  --           '<leader>un',
  --           function()
  --             Snacks.notifier.hide()
  --           end,
  --           desc = 'Dismiss All Notifications',
  --         },
  --         {
  --           '<c-/>',
  --           function()
  --             Snacks.terminal()
  --           end,
  --           desc = 'Toggle Terminal',
  --         },
  --         {
  --           '<c-_>',
  --           function()
  --             Snacks.terminal()
  --           end,
  --           desc = 'which_key_ignore',
  --         },
  --         {
  --           ']]',
  --           function()
  --             Snacks.words.jump(vim.v.count1)
  --           end,
  --           desc = 'Next Reference',
  --           mode = { 'n', 't' },
  --         },
  --         {
  --           '[[',
  --           function()
  --             Snacks.words.jump(-vim.v.count1)
  --           end,
  --           desc = 'Prev Reference',
  --           mode = { 'n', 't' },
  --         },
  --       },
  --       -- End Non Picker related key mappings  }}}
  --       init = function()
  --         vim.api.nvim_create_autocmd('User', {
  --           pattern = 'VeryLazy',
  --           callback = function()
  --             -- Setup some globals for debugging (lazy-loaded)
  --             _G.dd = function(...)
  --               Snacks.debug.inspect(...)
  --             end
  --             _G.bt = function()
  --               Snacks.debug.backtrace()
  --             end
  --             vim.print = _G.dd -- Override print to use snacks for `:=` command
  --
  --             -- Create some toggle mappings
  --             Snacks.toggle.option('spell', { name = 'Spelling' }):map '<leader>us'
  --             Snacks.toggle.option('wrap', { name = 'Wrap' }):map '<leader>uw'
  --             Snacks.toggle.option('relativenumber', { name = 'Relative Number' }):map '<leader>uL'
  --             Snacks.toggle.diagnostics():map '<leader>ud'
  --             Snacks.toggle.line_number():map '<leader>ul'
  --             Snacks.toggle.option('conceallevel', { off = 0, on = vim.o.conceallevel > 0 and vim.o.conceallevel or 2 }):map '<leader>uc'
  --             Snacks.toggle.treesitter():map '<leader>uT'
  --             Snacks.toggle.option('background', { off = 'light', on = 'dark', name = 'Dark Background' }):map '<leader>ub'
  --             Snacks.toggle.inlay_hints():map '<leader>uh'
  --             Snacks.toggle.indent():map '<leader>ug'
  --             Snacks.toggle.dim():map '<leader>uD'
  --           end,
  --         })
  --       end,
  --     },
  --   },
}
