repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
    language: system
    args:
      - --color=never
      - --exclude=SC1091
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=600]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: ^docs/docsite/(source|build)/
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        language: system
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
